#!/bin/busybox sh

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

for i in `seq 0 9` ; do
	# first stopp all the K?? scripts in this level
	for j in /etc/rcL.d/K$i[0-9]* ; do
		[ -f $j ] && $j stop
	done
	# start all S?? scripts in this level
	for j in /etc/rcL.d/S$i[0-9]* ; do
		[ -f $j ] && $j start
	done
done
exit 0

